api_url: "http://localhost:8000"

db_path: "data/nyc_taxi.db"

model_path: "models/taxi_model.pkl"
random_state: 42
test_size: 0.2

data_url: "https://github.com/eishkina-estia/ML2023/raw/main/data/New_York_City_Taxi_Trip_Duration.zip"
zip_path: "data/nyc_taxi.zip"
csv_train_path: "data/train.csv"
table_train: "train_data"
table_test: "test_data"
